### ISSUE TITLE
PubSub Impl

### ISSUE THREAD

**Issue by cretz** [Agorise/c-ipfs#1]
I know this is early work, just thought I'd mark it as an issue to support pubsub (no issues area on https://github.com/Agorise/c-libp2p). The libp2p specs are not clear here (ref: https://github.com/libp2p/specs/blob/master/4-architecture.md#451-pubsub) but the API iface is available (ref: https://github.com/ipfs/interface-ipfs-core/tree/master/API/pubsub).

Maybe should wait for it to solidify a bit, but definitely a worthy feature to support at some point.

**Comment by Agorise** [comment]
Issues area opened: https://github.com/Agorise/c-libp2p/issues 
 
PubSub will be supported if we need it for our projects and products. I have discussed this with the team here too. Will post more about that in our telegram group: http://t.me/Agorise 
 
Thanx for the feature request though @cretz much appreciated :)
