### ISSUE TITLE
OpenWRT package

### ISSUE THREAD

**Issue by renne** [Agorise/c-ipfs#14]
I suggest to offer an [OpenWRT](https://openwrt.org/) package. This will allow to use millions of routers as IPFS nodes.

**Comment by Agorise** [comment]
Agreed. Just doing some work with C-IPNS propagation right now first, and then more protocols for full compat with Go.

**Comment by marcialvieira** [comment]
Sending a compiled version that runs on OpenWRT for testing, remember that it is an initial project and is missing protocols, so it is still not compatible with go-ipfs and we don't know when it will be compatible.
[c-ipfs-662825493da4efb342740fd983d4f4528c65abf1-openwrt_musl_18.06.1_ar71xx.gz](https://github.com/Agorise/c-ipfs/files/2721438/c-ipfs-662825493da4efb342740fd983d4f4528c65abf1-openwrt_musl_18.06.1_ar71xx.gz)
