### ISSUE TITLE
Consider Alternative Build System

### ISSUE THREAD

**Issue by cretz** [Agorise/c-ipfs#2]
Something that will generate your makefiles (e.g. cmake, gyp, etc) or a different one altogether (e.g. ninja, pants, etc). I only ask as someone wanting Windows support. In the meantime, I can just use mingw because I know the path to Windows support has other issues (e.g. all of the posix socket stuff). 

Feel free to close if this not ever going to be a goal of the project.

**Comment by Agorise** [comment]
Well, yes and no... 
 
Once we have some builds out there that can be installed on Linux, Android and the Pi, we are going to give this product to the world in an announcement on steemit. It has been extremely expensive to get it this far, but it was needed for the other projects and products we are building and decentralizing. 
 
I would love to see builds for OpenWRT routers, full compatibility with the GO version of course, CJDNS support, I2P and Tor support and gui's that can work well with the Keybase guys. I'd love to share an IPFS hosted file with friends on KBFS... 
 
So, with that said, I will close this Issue, but please know that we are not dumping C-IPFS in any way, we are building it into all of our projects and products. For more info on what we are building, feel free to join us on Telegram: http://t.me/Agorise
