### ISSUE TITLE
The response is too slow: ipfs add/cat

### ISSUE THREAD

**Issue by unixyao** [Agorise/c-ipfs#8]
1. cat test.txt
Hello, C-IPFS! I am unixyao.

2. time ./ipfs add test.txt
{
	"ID": "<string>"
	"Type": "<int>"
	"Responses": [
		{
			"ID": "<string>"
			"Addrs": [
				"<object>"
			]
		}
	]
	"Extra": "<string>"
}
added QmQYSwoph7vnMzgbFUsLzwTxgbJsVpb9cRCLBVJ47qicGd test.txt

real	0m8.013s
user	0m0.016s
sys	0m0.000s

3. time ./ipfs cat QmQYSwoph7vnMzgbFUsLzwTxgbJsVpb9cRCLBVJ47qicGd
Hello, C-IPFS! I am unixyao.

real	0m6.017s
user	0m0.012s
sys	0m0.000s

**Comment by marcialvieira** [comment]
Yes, in the final phase, we should only try remote when needed, but at this point we need to focus on other points that are most needed, many changes are also needed, don't worry, log_* must be disabled in compilation and some other like stdio buffer replaced by unistd as a lightweight requirement and in my experience in another project almost 10 times faster bypassing the memory buffer.

**Comment by unixyao** [comment]
Thank you for your answer.
